#!/bin/bash
# tag all new main
/usr/bin/notmuch new

# Tag mailing lists and remove them from general inbox
notmuch tag -inbox +exwm to:exwm@noreply.github.com
notmuch tag -inbox +xelb to:xelb@noreply.github.com


# Me
notmuch tag -inbox +me from:cywinskimoss@gmail.com or from:wow.ethm@gmail.com

# google related
notmuch tag -inbox +google from:*@google.com
notmuch tag -inbox +google from:*@google.co.uk

# Family related emails.
## Familiy safety for the kids
notmuch tag -inbox -unread +familysafe from:families-noreply@google.com or from:familysafety@microsoft.com
notmuch tag -inbox +familysafe from:account-security-noreply@accountprotection.microsoft.com

## Family emails
notmuch tag -inbox +family from:lyndamiller1987@gmail.com
notmuch tag -inbox +appliance from:*@hotpointservice.co.uk

# Shopping and delivery information
## Amazon
notmuch tag -inbox -unread +shopping +amazon from:*@amazon.co.uk or from:*@amazon.com

## Ebay
notmuch tag -inbox -unread +shopping +ebay from:*ebay.co.uk or from:*ebay.com

## Autotrader listings
notmuch tag -inbox +autotrader from:*@service.autotrader.co.uk

## Ali Express
notmuch tag -inbox -unread +aliexpress +marketing from:*@deals.aliexpress.com

## PCB way
notmuch tag -inbox -unread +pcbway from:*@pcbway.com

# Finances
## Banking
notmuch tag -inbox +finance +bank from:donotreply@lloydsbank.co*
notmuch tag -inbox -unread +finance +bank from:info@emails.lloydsbank.co*
notmuch tag -inbox -unread from:googlewallet-noreply@google.com
notmuch tag +finance -unread tag:google from:googleplay-noreply@google*

## Mobiles
### O2
notmuch tag -inbox -unread +o2 +sims from:*@s-email-o2.co.uk
notmuch tag -inbox -unread +o2 +sims from:*@o2-welcome.com
notmuch tag +finance +bill tag:o2 from:"O2 Billing"

### Vodafone
notmuch -inbox -unread +vodafone from:*@help.vodafone.co.uk
notmuch -inbox -unread +vodafone from:*@email.vodafone.co.uk

## Virgin media
notmuch tag -inbox -unread +virgin +internet from:*@virginmedia.co.uk

## EON next
notmuch tag -inbox -unread +eon +energy from:hi@eonnext.com
notmuch tag +bill tag:eon and subject:"FYI: Your energy statement"

## paypal
notmuch tag -inbox -unread +receipt +paypal from:service@paypal.co.uk

## Uber eats
notmuch tag -inbox -unread +receipt +uber from:"Uber Receipts"

## clearscore
notmuch tag -inbox +clearscore from:"Clearscore"
notmuch tag -unread +marketing tag:clearscore and from:marketing@clearscore.com

## Trading 212
notmuch tag -inbox -unread +marketing +stocks from:*@trading212.co*

## Website (domain ect)
notmuch tag -inbox -unread +domain +marketing from:*@mail.squarespace.com
notmuch tag -inbox +domain from:*@squarespace.com

# Uni related emails
## Open uni
notmuch tag -inbox +uni from:*@open.ac.uk
notmuch tag -inbox -unread +uni from:*@info.open.ac.uk or from:info@mail.openuniversity.co.uk
notmuch tag +important from:ETMA-Admin@open.ac.uk

## Cisco
notmuch tag -inbox -unread from:netacademail@external.cisco.co.uk or from:netacademail@external.cisco.com

# health related
notmuch tag -inbox +dentist from:Braintree@mail.together.dental
notmuch tag -inbox +fitbit from:*@fitbit.com
notmuch tag -inbox +cats from:*@animalfriends.co*

# Entertainment
notmuch tag -inbox -unread +chess from:*@chess.com
notmuch tag -inbox -unread +steam from:*@steam*
notmuch tag -inbox +youtube from:*@youtube.co.uk or from:*@youtube.com
notmuch tag -inbox -unread +ea from:EA@e.ea.com
notmuch tag -inbox -unread +g2a from:*@g2a.com


# Gov
notmuch tag +gov from:*.gov.uk

# AI
notmuch tag -inbox -unread +ai from:googleaistudio-noreply@google.com
notmuch tag -inbox -unread +ai from:google-gemini-noreply@google.com

# Unwanted
notmuch tag -inbox -unread +tfl from:*@email.tfl.gov.uk
notmuch tag -inbox -unread +halfords from:*halfords.com or from:*halfords.co.uk
notmuch tag -inbox -unread +marketing from:*@email.oneplus.co*
notmuch tag -inbox -unread +newsletter from:newsletter*
