#! /bin/bash

array=("Volume" "Brightness")
summary=$(echo $2 | awk -F ' ' '{print $1}')

if [[ ! " ${array[*]} " =~ " ${summary} " ]]; then
    paplay $XDG_CONFIG_HOME/dunst/sounds/beep_normal.ogg
fi

