#! /bin/bash
function reload() {
    source ~/.bashrc
}

# function emacs() {
#     args=""
#     # if called without arguments - open a new instance
#     if [ "$#" -eq "0" ]; then
# 	    args=(-c $args) 		# open emacsclient in a new window
#     fi
#     if [ "$#" -gt "0" ]; then
# 	    if [[ "$1" == "-" ]]; then
#     	    TMP="$(mktemp $TMPDIR/emacsstdin-XXX)"
#     	    cat >$TMP
# 	        args=($args --eval '(let ((b (generate-new-buffer "*stdin*"))) (switch-to-buffer b) (insert-file-contents "'${TMP}'") (delete-file "'${TMP}'"))')
# 	    else
# 	        args=($@ $args)
# 	    fi
#     fi
#     emacsclient "${args[@]}"
# }
